name: Build and Release

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    name: Build on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: AMD64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            arch: ARM64
          - os: macos-latest
            target: x86_64-apple-darwin
            arch: AMD64
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: ARM64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: AMD64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: target/${{ matrix.target }}/release/shopify_theme_cleaner
